// Auto-generated by scripts/build-articles.mjs — do not edit
export const ARTICLE_ROUTES = {
  "100-bonus-nuhtsul": {
    "mn": "100-bonus-nuhtsul",
    "en": "100-deposit-bonus",
    "ru": "bonus-100-usloviya",
    "zh": "100-cunkuan-jiangjin"
  },
  "3bet-4bet-mongol": {
    "mn": "3bet-4bet-mongol"
  },
  "bankroll-udirdlaga": {
    "mn": "bankroll-udirdlaga",
    "en": "bankroll-management",
    "ru": "bankroll-menedzhment",
    "zh": "bankroll-guanli"
  },
  "bet-hmjuulelt": {
    "mn": "bet-hmjuulelt"
  },
  "blaynd-togloom": {
    "mn": "blaynd-togloom"
  },
  "blef-uriag": {
    "mn": "blef-uriag",
    "en": "art-of-bluffing",
    "ru": "iskusstvo-blufa",
    "zh": "zhapian-zhishu"
  },
  "bluff-poker-mongolia": {
    "mn": "bluff-poker-mongolia",
    "en": "bluff-poker-mongolia",
    "ru": "bluff-poker-mongolia",
    "zh": "bluff-poker-mongolia"
  },
  "burtgel-alham-alham": {
    "mn": "burtgel-alham-alham"
  },
  "cash-game-mongol": {
    "mn": "cash-game-mongol",
    "en": "cash-game-mongolia",
    "ru": "kesh-igry-mongoliya",
    "zh": "xianjin-zhuo-mongolia"
  },
  "cbet-strategi": {
    "mn": "cbet-strategi"
  },
  "check-raise-taktik": {
    "mn": "check-raise-taktik"
  },
  "club-vs-platform": {
    "mn": "club-vs-platform"
  },
  "dans-hamgaalalt": {
    "mn": "dans-hamgaalalt"
  },
  "deposit-withdraw-mongol": {
    "mn": "deposit-withdraw-mongol",
    "en": "deposit-withdraw-mongolia",
    "ru": "deposit-vyvod-mongoliya",
    "zh": "cunkuan-tikuan-mongolia"
  },
  "ehnii-gar-songolt": {
    "mn": "ehnii-gar-songolt",
    "en": "starting-hand-selection",
    "ru": "vybor-startovykh-ruk",
    "zh": "qishou-pai-xuanze"
  },
  "exploitation-taktik": {
    "mn": "exploitation-taktik"
  },
  "floating-taktik": {
    "mn": "floating-taktik",
    "en": "floating-strategy",
    "ru": "strategiya-float",
    "zh": "float-celue"
  },
  "hariutslagatai-togloom": {
    "mn": "hariutslagatai-togloom"
  },
  "holdem-durem-buren": {
    "mn": "holdem-durem-buren"
  },
  "holdem-vs-omaha": {
    "mn": "holdem-vs-omaha",
    "en": "holdem-vs-omaha",
    "ru": "holdem-vs-omaha",
    "zh": "holdem-vs-omaha"
  },
  "hud-vpip-pfr": {
    "mn": "hud-vpip-pfr"
  },
  "mongol-poker-sistem": {
    "mn": "mongol-poker-sistem",
    "en": "mongol-poker-system",
    "ru": "mongol-poker-sistema",
    "zh": "mongol-poker-xitong"
  },
  "mongol-poker-tatah": {
    "mn": "mongol-poker-tatah",
    "en": "mongol-poker-download",
    "ru": "mongol-poker-skachat",
    "zh": "mongol-poker-xiazai"
  },
  "multiway-pot": {
    "mn": "multiway-pot"
  },
  "omaha-durem-buren": {
    "mn": "omaha-durem-buren"
  },
  "online-poker-mongol-2026": {
    "mn": "online-poker-mongol-2026",
    "en": "online-poker-mongolia-2026",
    "ru": "online-poker-mongoliya-2026",
    "zh": "online-poker-mongolia-2026"
  },
  "plo-draw-buren": {
    "mn": "plo-draw-buren"
  },
  "plo-ehnii-gar": {
    "mn": "plo-ehnii-gar"
  },
  "poker-kombinatsiud": {
    "mn": "poker-kombinatsiud",
    "en": "poker-hand-rankings",
    "ru": "poker-kombinatsii",
    "zh": "poker-shoupai-paiming"
  },
  "poker-setgel-zui": {
    "mn": "poker-setgel-zui",
    "en": "poker-psychology-mindset",
    "ru": "psihologiya-pokera",
    "zh": "poker-xinlixue"
  },
  "poker-terms-mn": {
    "mn": "poker-terms-mn",
    "en": "poker-terms-glossary",
    "ru": "poker-terminy-slovar",
    "zh": "poker-shuyu-cidian"
  },
  "postflop-suuri": {
    "mn": "postflop-suuri"
  },
  "pot-odds-equity": {
    "mn": "pot-odds-equity"
  },
  "pozitsiin-huch": {
    "mn": "pozitsiin-huch",
    "en": "table-position-poker",
    "ru": "pozitsiya-v-pokere",
    "zh": "zhuo-shang-weizhi"
  },
  "pppoker-app-aldaa": {
    "mn": "pppoker-app-aldaa"
  },
  "pppoker-klub-vs-betting": {
    "mn": "pppoker-klub-vs-betting",
    "en": "pppoker-club-vs-betting",
    "ru": "pppoker-klub-vs-bukmeker",
    "zh": "pppoker-klub-vs-touzhu"
  },
  "preflop-strategi": {
    "mn": "preflop-strategi"
  },
  "range-unshih": {
    "mn": "range-unshih"
  },
  "statistik-analiz": {
    "mn": "statistik-analiz",
    "en": "poker-statistics-analysis",
    "ru": "statistika-pokera",
    "zh": "poker-tongji-fenxi"
  },
  "steal-resteal": {
    "mn": "steal-resteal"
  },
  "tatalt-asuudal-shiidver": {
    "mn": "tatalt-asuudal-shiidver"
  },
  "turn-river-play": {
    "mn": "turn-river-play"
  },
  "usdt-deposit-zaavar": {
    "mn": "usdt-deposit-zaavar"
  },
  "vip-shiree-mongol": {
    "mn": "vip-shiree-mongol"
  }
}

export function articlesHubPath(lang) {
  return lang === 'mn' ? '/articles/' : `/${lang}/articles/`
}

export function articlePath(groupId, lang) {
  const group = ARTICLE_ROUTES[groupId]
  if (!group) return null
  const slug = group[lang] || group.mn
  if (!slug) return null
  return lang === 'mn' ? `/articles/${slug}/` : `/${lang}/articles/${slug}/`
}
