// Auto-generated by scripts/build-articles.mjs — do not edit
export const ARTICLE_ROUTES = {
  "100-bonus-nuhtsul": {
    "mn": "100-bonus-nuhtsul",
    "en": "100-deposit-bonus",
    "ru": "bonus-100-usloviya",
    "zh": "100-cunkuan-jiangjin"
  },
  "3bet-4bet-mongol": {
    "mn": "3bet-4bet-mongol",
    "en": "3bet-4bet-strategy",
    "ru": "3bet-4bet-strategiya",
    "zh": "3bet-4bet-celue"
  },
  "baatryn-oroo-taniltsuulga": {
    "mn": "baatryn-oroo-taniltsuulga",
    "en": "baatryn-oroo-intro",
    "ru": "baatryn-oroo-klub",
    "zh": "baatryn-oroo-jieshao"
  },
  "bankroll-udirdlaga": {
    "mn": "bankroll-udirdlaga",
    "en": "bankroll-management",
    "ru": "bankroll-menedzhment",
    "zh": "bankroll-guanli"
  },
  "bet-hmjuulelt": {
    "mn": "bet-hmjuulelt",
    "en": "bet-sizing-poker",
    "ru": "razmer-stavok-poker",
    "zh": "xiazhu-daxiao"
  },
  "blaynd-togloom": {
    "mn": "blaynd-togloom"
  },
  "blef-uriag": {
    "mn": "blef-uriag",
    "en": "art-of-bluffing",
    "ru": "iskusstvo-blufa",
    "zh": "zhapian-zhishu"
  },
  "bluff-poker-mongolia-yu-ve": {
    "mn": "bluff-poker-mongolia-yu-ve",
    "en": "what-is-bluff-poker-mongolia"
  },
  "bluff-poker-mongolia": {
    "mn": "bluff-poker-mongolia",
    "en": "bluff-poker-mongolia",
    "ru": "bluff-poker-mongolia",
    "zh": "bluff-poker-mongolia"
  },
  "burtgel-alham-alham": {
    "mn": "burtgel-alham-alham",
    "en": "registration-step-by-step",
    "ru": "registratsiya-poshagovo",
    "zh": "zhuce-buzhou"
  },
  "cash-game-mongol": {
    "mn": "cash-game-mongol",
    "en": "cash-game-mongolia",
    "ru": "kesh-igry-mongoliya",
    "zh": "xianjin-zhuo-mongolia"
  },
  "cbet-strategi": {
    "mn": "cbet-strategi",
    "en": "cbet-strategy",
    "ru": "cbet-strategiya",
    "zh": "cbet-celue"
  },
  "check-raise-taktik": {
    "mn": "check-raise-taktik",
    "en": "check-raise-tactics",
    "ru": "check-raise-taktika",
    "zh": "check-raise-zhanfa"
  },
  "club-vs-platform": {
    "mn": "club-vs-platform",
    "en": "club-vs-platform",
    "ru": "klub-vs-platforma",
    "zh": "julebu-vs-pingtai"
  },
  "dans-hamgaalalt": {
    "mn": "dans-hamgaalalt",
    "en": "account-security",
    "ru": "bezopasnost-akkaunta",
    "zh": "zhanghu-anquan"
  },
  "deposit-withdraw-mongol": {
    "mn": "deposit-withdraw-mongol",
    "en": "deposit-withdraw-mongolia",
    "ru": "deposit-vyvod-mongoliya",
    "zh": "cunkuan-tikuan-mongolia"
  },
  "ehnii-gar-songolt": {
    "mn": "ehnii-gar-songolt",
    "en": "starting-hand-selection",
    "ru": "vybor-startovykh-ruk",
    "zh": "qishou-pai-xuanze"
  },
  "expat-poker-mongol": {
    "mn": "expat-poker-mongol",
    "en": "expat-poker-mongolia",
    "ru": "eksapat-poker-mongoliya",
    "zh": "waiguo-poker-menggu"
  },
  "exploitation-taktik": {
    "mn": "exploitation-taktik"
  },
  "floating-taktik": {
    "mn": "floating-taktik",
    "en": "floating-strategy",
    "ru": "strategiya-float",
    "zh": "float-celue"
  },
  "hariutslagatai-togloom": {
    "mn": "hariutslagatai-togloom",
    "en": "responsible-gaming",
    "ru": "otvetstvennaya-igra",
    "zh": "fuze-renyouxi"
  },
  "high-stakes-vip": {
    "mn": "high-stakes-vip",
    "en": "high-stakes-vip",
    "ru": "high-stakes-vip",
    "zh": "gaoe-zhuo-vip"
  },
  "holdem-durem-buren": {
    "mn": "holdem-durem-buren",
    "en": "holdem-rules-complete",
    "ru": "holdem-pravila-polnostyu",
    "zh": "holdem-guize-quan"
  },
  "holdem-vs-omaha": {
    "mn": "holdem-vs-omaha",
    "en": "holdem-vs-omaha",
    "ru": "holdem-vs-omaha",
    "zh": "holdem-vs-omaha"
  },
  "hud-vpip-pfr": {
    "mn": "hud-vpip-pfr"
  },
  "huudas-songolt": {
    "mn": "huudas-songolt",
    "en": "table-selection-poker",
    "ru": "vybor-stola-poker",
    "zh": "xuanze-zhuozi"
  },
  "megamax-poker-mongolia": {
    "mn": "megamax-poker-mongolia",
    "en": "megamax-poker-mongolia"
  },
  "micro-stakes-250-500": {
    "mn": "micro-stakes-250-500",
    "en": "micro-stakes-250-500",
    "ru": "micro-stavki-250-500",
    "zh": "wei-xiaozhu-250-500"
  },
  "mobile-vs-desktop": {
    "mn": "mobile-vs-desktop",
    "en": "mobile-vs-desktop-poker",
    "ru": "mobil-vs-desktop",
    "zh": "shouji-vs-diannao"
  },
  "mongol-poker-sistem": {
    "mn": "mongol-poker-sistem",
    "en": "mongol-poker-system",
    "ru": "mongol-poker-sistema",
    "zh": "mongol-poker-xitong"
  },
  "mongol-poker-tatah": {
    "mn": "mongol-poker-tatah",
    "en": "mongol-poker-download",
    "ru": "mongol-poker-skachat",
    "zh": "mongol-poker-xiazai"
  },
  "mongol-tulbur-arga": {
    "mn": "mongol-tulbur-arga",
    "en": "mongolia-payment-methods",
    "ru": "mongolskie-platezhi",
    "zh": "menggu-zhifu-fangshi"
  },
  "multiway-pot": {
    "mn": "multiway-pot",
    "en": "multiway-pot",
    "ru": "multiway-pot",
    "zh": "duoren-chi"
  },
  "omaha-durem-buren": {
    "mn": "omaha-durem-buren",
    "en": "omaha-rules-complete",
    "ru": "omaha-pravila-polnostyu",
    "zh": "omaha-guize-quan"
  },
  "one-king-poker-mongolia": {
    "mn": "one-king-poker-mongolia",
    "en": "one-king-poker-mongolia"
  },
  "online-poker-mongol-2026": {
    "mn": "online-poker-mongol-2026",
    "en": "online-poker-mongolia-2026",
    "ru": "online-poker-mongoliya-2026",
    "zh": "online-poker-mongolia-2026"
  },
  "plo-draw-buren": {
    "mn": "plo-draw-buren"
  },
  "plo-ehnii-gar": {
    "mn": "plo-ehnii-gar"
  },
  "poker-kombinatsiud": {
    "mn": "poker-kombinatsiud",
    "en": "poker-hand-rankings",
    "ru": "poker-kombinatsii",
    "zh": "poker-shoupai-paiming"
  },
  "poker-setgel-zui": {
    "mn": "poker-setgel-zui",
    "en": "poker-psychology-mindset",
    "ru": "psihologiya-pokera",
    "zh": "poker-xinlixue"
  },
  "poker-soyol-online": {
    "mn": "poker-soyol-online",
    "en": "online-poker-etiquette",
    "ru": "etiket-onlayn-pokera",
    "zh": "zaixian-poker-liyi"
  },
  "poker-terms-mn": {
    "mn": "poker-terms-mn",
    "en": "poker-terms-glossary",
    "ru": "poker-terminy-slovar",
    "zh": "poker-shuyu-cidian"
  },
  "pokermongolia-com-yu-ve": {
    "mn": "pokermongolia-com-yu-ve",
    "en": "what-is-pokermongolia-com"
  },
  "postflop-suuri": {
    "mn": "postflop-suuri",
    "en": "postflop-basics",
    "ru": "postflop-osnovy",
    "zh": "houfan-jichu"
  },
  "pot-odds-equity": {
    "mn": "pot-odds-equity",
    "en": "pot-odds-equity",
    "ru": "pot-odds-ekviti",
    "zh": "pot-odds-quanyi"
  },
  "pozitsiin-huch": {
    "mn": "pozitsiin-huch",
    "en": "table-position-poker",
    "ru": "pozitsiya-v-pokere",
    "zh": "zhuo-shang-weizhi"
  },
  "pppoker-app-aldaa": {
    "mn": "pppoker-app-aldaa",
    "en": "pppoker-app-errors",
    "ru": "pppoker-oshibki-prilozheniya",
    "zh": "pppoker-yingyong-cuowu"
  },
  "pppoker-klub-vs-betting": {
    "mn": "pppoker-klub-vs-betting",
    "en": "pppoker-club-vs-betting",
    "ru": "pppoker-klub-vs-bukmeker",
    "zh": "pppoker-klub-vs-touzhu"
  },
  "pppoker-vs-pokerstars-mongol": {
    "mn": "pppoker-vs-pokerstars-mongol",
    "en": "pppoker-vs-pokerstars-mongolia"
  },
  "preflop-strategi": {
    "mn": "preflop-strategi",
    "en": "preflop-strategy",
    "ru": "preflop-strategiya",
    "zh": "qianfan-choulu"
  },
  "range-unshih": {
    "mn": "range-unshih",
    "en": "reading-poker-ranges",
    "ru": "chtenie-range",
    "zh": "yuedu-range"
  },
  "statistik-analiz": {
    "mn": "statistik-analiz",
    "en": "poker-statistics-analysis",
    "ru": "statistika-pokera",
    "zh": "poker-tongji-fenxi"
  },
  "steal-resteal": {
    "mn": "steal-resteal"
  },
  "tatalt-asuudal-shiidver": {
    "mn": "tatalt-asuudal-shiidver",
    "en": "withdrawal-issues",
    "ru": "problemy-vyvoda",
    "zh": "tikuan-wenti"
  },
  "turbo-poker-mongolia": {
    "mn": "turbo-poker-mongolia",
    "en": "turbo-poker-mongolia"
  },
  "turn-river-play": {
    "mn": "turn-river-play",
    "en": "turn-river-play",
    "ru": "turn-river-igra",
    "zh": "turn-river-wanfa"
  },
  "ulaanbaatar-poker-2026": {
    "mn": "ulaanbaatar-poker-2026",
    "en": "ulaanbaatar-poker-2026",
    "ru": "ulaanbaatar-poker-2026",
    "zh": "ulanbator-poker-2026"
  },
  "usdt-deposit-zaavar": {
    "mn": "usdt-deposit-zaavar",
    "en": "usdt-deposit-guide",
    "ru": "usdt-depozit-gaid",
    "zh": "usdt-cunkuan-zhinan"
  },
  "variance-poker": {
    "mn": "variance-poker",
    "en": "poker-variance",
    "ru": "variance-poker",
    "zh": "poker-fangcha"
  },
  "vip-shiree-mongol": {
    "mn": "vip-shiree-mongol",
    "en": "vip-table-mongolia",
    "ru": "vip-stol-mongoliya",
    "zh": "vip-zhuo-menggu"
  }
}

export function articlesHubPath(lang) {
  return lang === 'mn' ? '/articles/' : `/${lang}/articles/`
}

export function articlePath(groupId, lang) {
  const group = ARTICLE_ROUTES[groupId]
  if (!group) return null
  const slug = group[lang] || group.mn
  if (!slug) return null
  return lang === 'mn' ? `/articles/${slug}/` : `/${lang}/articles/${slug}/`
}
